Pool Games: CRandom Class Reference
CRandom Class Reference
Contract for SELDOM generation random number by request based on Tezos blocks.
Classes
struct t_future
For what time a random number is needed.
struct t_ifuture
Types for contract storage.
struct t_storage
Contract storage.
Public Types
enum t_entrypoint {
CreateFuture , DeleteFuture , GetFuture , FillFuture ,
ForceDeleteFuture
}
All entrypoints of contract.
typedef pair< t_operations, t_storage > t_return
The returned result of the contract.
typedef big_map< t_ifuture, t_future > t_futures
Structures for future callback orders.
Public Member Functions
t_future getFuture (const t_storage s, const t_ifuture ifuture)
Getting a random number with an error if not found.
t_return main (const t_entrypoint entrypoint, t_storage s)
Single entry point of the contract.
Public Attributes
const compileTimeError cteAdminOrAdmins = "Compile time error: Must be ENABLE_ADMIN or ENABLE_ADMINS, not together"
Must be ENABLE_ADMIN or ENABLE_ADMINS, not together.
const compileTimeError cteOwnerOrAdmins = "Compile time error: Must be ENABLE_OWNER or ENABLE_ADMIN or ENABLE_ADMINS"
Must be ENABLE_OWNER or ENABLE_ADMIN or ENABLE_ADMINS.
const string cERR_ONLY_FUTURE = "OnlyFuture"
Error: The order time of a random number should be in the future.
const string cERR_NOT_FOUND = "NotFound"
Error: No random number found.
const string cERR_EARLY = "Early"
Error: Early filling random number.
const string cERR_NOT_READY = "NotReady"
Error: Random number not received yet.
Detailed Description
Contract for SELDOM generation random number by request based on Tezos blocks.
Definition at line 8 of file CRandom/access.ligo.
Member Typedef Documentation
t_futures
typedef big_map<t_ifuture,t_future> CRandom::t_futures
Structures for future callback orders.
Definition at line 47 of file CRandom/types.ligo.
t_return
typedef pair<t_operations,t_storage> CRandom::t_return
The returned result of the contract.
Definition at line 23 of file CRandom/storage.ligo.
Member Enumeration Documentation
t_entrypoint
enum CRandom::t_entrypoint
All entrypoints of contract.
Enumerator
CreateFuture
Creating a request for a random number.
DeleteFuture
Deleting a request for a random number.
GetFuture
Random Number Request.
FillFuture
Filling in a random number.
ForceDeleteFuture
Forced deletion of a request for a random number by the contract admin.
Definition at line 13 of file CRandom.ligo.
Member Function Documentation
getFuture()
t_future CRandom::getFuture (const t_storage s, const t_ifuture ifuture) inline
Getting a random number with an error if not found.
Definition at line 78 of file CRandom.ligo.
References cERR_NOT_FOUND, and CRandom::t_storage::futures.
Referenced by main().
main()
t_return CRandom::main (const t_entrypoint entrypoint, t_storage s) inline
Single entry point of the contract.
Definition at line 86 of file CRandom.ligo.
References MOwner::accessChange(), CRandom::t_storage::admin, cERR_EARLY, cERR_NOT_FOUND, cERR_NOT_READY, cERR_ONLY_FUTURE, cNO_OPERATIONS, CreateFuture, DeleteFuture, ENABLE_ADMIN, ENABLE_ADMINS, FillFuture, MAdmins::forceAdd(), ForceDeleteFuture, MAdmins::forceRem(), CRandom::t_storage::futures, GetFuture, getFuture(), CRandom::t_storage::owner, CRandom::t_ifuture::ts, and CRandom::t_future::tsLevel.
Member Data Documentation
cERR_EARLY
const string CRandom::cERR_EARLY = "Early"
Error: Early filling random number.
Definition at line 70 of file CRandom.ligo.
Referenced by main().
cERR_NOT_FOUND
const string CRandom::cERR_NOT_FOUND = "NotFound"
Error: No random number found.
Definition at line 66 of file CRandom.ligo.
Referenced by getFuture(), and main().
cERR_NOT_READY
const string CRandom::cERR_NOT_READY = "NotReady"
Error: Random number not received yet.
Definition at line 74 of file CRandom.ligo.
Referenced by main().
cERR_ONLY_FUTURE
const string CRandom::cERR_ONLY_FUTURE = "OnlyFuture"
Error: The order time of a random number should be in the future.
Definition at line 62 of file CRandom.ligo.
Referenced by main().
cteAdminOrAdmins
const compileTimeError CRandom::cteAdminOrAdmins = "Compile time error: Must be ENABLE_ADMIN or ENABLE_ADMINS, not together"
Must be ENABLE_ADMIN or ENABLE_ADMINS, not together.
Definition at line 38 of file CRandom/config.ligo.
cteOwnerOrAdmins
const compileTimeError CRandom::cteOwnerOrAdmins = "Compile time error: Must be ENABLE_OWNER or ENABLE_ADMIN or ENABLE_ADMINS"
Must be ENABLE_OWNER or ENABLE_ADMIN or ENABLE_ADMINS.
Definition at line 44 of file CRandom/config.ligo.
The documentation for this class was generated from the following files:
CRandom/access.ligo
CRandom/storage.ligo
CRandom/types.ligo
CRandom/config.ligo
CRandom.ligo