Pool Games: MFarmCrunchy Class Reference
MFarmCrunchy Class Reference
Crunchy Farm Interaction Module.
Classes
struct t_deposit_params
Parameters for the deposit to the Crunchy farm.
struct t_withdraw_params
Parameters for extracting a deposit from a Crunchy farm.
Public Types
typedef nat t_farm_id
Crunchy farm ID.
typedef CrunchyDeposit of t_deposit_params t_deposit_method
Prototype of the Crunchy farm deposit method.
typedef contract< t_deposit_method > t_deposit_contract
Contract with deposit entry point in Crunchy farm format.
typedef CrunchyWithdraw of t_withdraw_params t_withdraw_method
Prototype of the Crunchy farm withdrawal method.
typedef contract< t_withdraw_method > t_withdraw_contract
Contract with withdrawal entry point in Crunchy farm format.
typedef t_farm_id t_harvest_params
Parameters for receiving rewards from the Crunchy farm.
typedef CrunchyHarvest of t_harvest_params t_harvest_method
Prototype of the Crunchy farm harvest method.
typedef contract< t_harvest_method > t_harvest_contract
A contract with the harvest entry point in the Crunchy farm format.
Public Member Functions
t_deposit_contract depositEntrypoint (const address addr)
Get the deposit farm entry point with the Crunchy interface.
t_deposit_method depositParams (const t_farm_id farm_id, const MToken::t_amount damount)
Parameters for the deposit Crunchy method.
operation deposit (const address addr, const t_farm_id farm_id, const MToken::t_amount damount)
Deposit to Crunchy farm.
t_withdraw_contract withdrawEntrypoint (const address addr)
Get the withdrawal farm entry point with the Crunchy interface.
t_withdraw_method withdrawParams (const t_farm_id farm_id, const MToken::t_amount wamount)
Parameters for the withdraw Crunchy method.
operation withdraw (const address addr, const t_farm_id farm_id, const MToken::t_amount wamount)
Extracting a deposit from a Crunchy farm.
t_harvest_contract harvestEntrypoint (const address addr)
Get the harvest farm entry point with the Crunchy interface.
t_harvest_method harvestParams (const t_farm_id farm_id)
Parameters for the harvest Crunchy method.
operation harvest (const address addr, const t_farm_id farm_id)
Getting Rewards from Crunchy arm.
unit check (const address addr)
Checking the farm parameters for validity.
Public Attributes
const string cERR_NOT_FOUND_DEPOSIT = "MFarmCrunchy/NotFoundDeposit"
Error: Deposit entry point for Crunchy farm not found.
const string cERR_NOT_FOUND_WITHDRAW = "MFarmCrunchy/NotFoundWithdraw"
Error: Withdrawal entry point not found for Crunchy farm.
const string cERR_NOT_FOUND_HARVEST = "MFarmCrunchy/NotFoundHarvest"
Error: No harvest entry point found for Crunchy farm.
Detailed Description
Crunchy Farm Interaction Module.
Definition at line 8 of file MFarmCrunchy.ligo.
Member Typedef Documentation
t_deposit_contract
typedef contract<t_deposit_method> MFarmCrunchy::t_deposit_contract
Contract with deposit entry point in Crunchy farm format.
Definition at line 37 of file MFarmCrunchy.ligo.
t_deposit_method
typedef CrunchyDeposit of t_deposit_params MFarmCrunchy::t_deposit_method
Prototype of the Crunchy farm deposit method.
Definition at line 33 of file MFarmCrunchy.ligo.
t_farm_id
typedef nat MFarmCrunchy::t_farm_id
Crunchy farm ID.
Definition at line 22 of file MFarmCrunchy.ligo.
t_harvest_contract
typedef contract<t_harvest_method> MFarmCrunchy::t_harvest_contract
A contract with the harvest entry point in the Crunchy farm format.
Definition at line 64 of file MFarmCrunchy.ligo.
t_harvest_method
typedef CrunchyHarvest of t_harvest_params MFarmCrunchy::t_harvest_method
Prototype of the Crunchy farm harvest method.
Definition at line 60 of file MFarmCrunchy.ligo.
t_harvest_params
typedef t_farm_id MFarmCrunchy::t_harvest_params
Parameters for receiving rewards from the Crunchy farm.
Definition at line 56 of file MFarmCrunchy.ligo.
t_withdraw_contract
typedef contract<t_withdraw_method> MFarmCrunchy::t_withdraw_contract
Contract with withdrawal entry point in Crunchy farm format.
Definition at line 52 of file MFarmCrunchy.ligo.
t_withdraw_method
typedef CrunchyWithdraw of t_withdraw_params MFarmCrunchy::t_withdraw_method
Prototype of the Crunchy farm withdrawal method.
Definition at line 48 of file MFarmCrunchy.ligo.
Member Function Documentation
check()
unit MFarmCrunchy::check (const address addr) inline
Checking the farm parameters for validity.
Definition at line 139 of file MFarmCrunchy.ligo.
References depositEntrypoint(), harvestEntrypoint(), and withdrawEntrypoint().
Referenced by MFarm::check().
deposit()
operation MFarmCrunchy::deposit (const address addr, const t_farm_id farm_id, const MToken::t_amount damount) inline
Deposit to Crunchy farm.
Definition at line 84 of file MFarmCrunchy.ligo.
References depositEntrypoint(), and depositParams().
Referenced by MFarm::deposit().
depositEntrypoint()
t_deposit_contract MFarmCrunchy::depositEntrypoint (const address addr) inline
Get the deposit farm entry point with the Crunchy interface.
Definition at line 68 of file MFarmCrunchy.ligo.
References cERR_NOT_FOUND_DEPOSIT.
Referenced by check(), and deposit().
depositParams()
t_deposit_method MFarmCrunchy::depositParams (const t_farm_id farm_id, const MToken::t_amount damount) inline
Parameters for the deposit Crunchy method.
Definition at line 76 of file MFarmCrunchy.ligo.
Referenced by deposit().
harvest()
operation MFarmCrunchy::harvest (const address addr, const t_farm_id farm_id) inline
Getting Rewards from Crunchy arm.
Definition at line 130 of file MFarmCrunchy.ligo.
References harvestEntrypoint(), and harvestParams().
Referenced by MFarm::harvest().
harvestEntrypoint()
t_harvest_contract MFarmCrunchy::harvestEntrypoint (const address addr) inline
Get the harvest farm entry point with the Crunchy interface.
Definition at line 118 of file MFarmCrunchy.ligo.
References cERR_NOT_FOUND_HARVEST.
Referenced by check(), and harvest().
harvestParams()
t_harvest_method MFarmCrunchy::harvestParams (const t_farm_id farm_id) inline
Parameters for the harvest Crunchy method.
Definition at line 126 of file MFarmCrunchy.ligo.
Referenced by harvest().
withdraw()
operation MFarmCrunchy::withdraw (const address addr, const t_farm_id farm_id, const MToken::t_amount wamount) inline
Extracting a deposit from a Crunchy farm.
Definition at line 109 of file MFarmCrunchy.ligo.
References withdrawEntrypoint(), and withdrawParams().
Referenced by MFarm::withdraw().
withdrawEntrypoint()
t_withdraw_contract MFarmCrunchy::withdrawEntrypoint (const address addr) inline
Get the withdrawal farm entry point with the Crunchy interface.
Definition at line 93 of file MFarmCrunchy.ligo.
References cERR_NOT_FOUND_WITHDRAW.
Referenced by check(), and withdraw().
withdrawParams()
t_withdraw_method MFarmCrunchy::withdrawParams (const t_farm_id farm_id, const MToken::t_amount wamount) inline
Parameters for the withdraw Crunchy method.
Definition at line 101 of file MFarmCrunchy.ligo.
Referenced by withdraw().
Member Data Documentation
cERR_NOT_FOUND_DEPOSIT
const string MFarmCrunchy::cERR_NOT_FOUND_DEPOSIT = "MFarmCrunchy/NotFoundDeposit"
Error: Deposit entry point for Crunchy farm not found.
Definition at line 12 of file MFarmCrunchy.ligo.
Referenced by depositEntrypoint().
cERR_NOT_FOUND_HARVEST
const string MFarmCrunchy::cERR_NOT_FOUND_HARVEST = "MFarmCrunchy/NotFoundHarvest"
Error: No harvest entry point found for Crunchy farm.
Definition at line 20 of file MFarmCrunchy.ligo.
Referenced by harvestEntrypoint().
cERR_NOT_FOUND_WITHDRAW
const string MFarmCrunchy::cERR_NOT_FOUND_WITHDRAW = "MFarmCrunchy/NotFoundWithdraw"
Error: Withdrawal entry point not found for Crunchy farm.
Definition at line 16 of file MFarmCrunchy.ligo.
Referenced by withdrawEntrypoint().
The documentation for this class was generated from the following file:
MFarmCrunchy.ligo