Pool Games: MFarm Class Reference
MFarm Class Reference
Farm Interaction Module.
Classes
struct t_farm
Farm Parameters.
Public Types
enum t_interface { InterfaceCrunchy , InterfaceQUIPU }
Farm interfaces.
Public Member Functions
unit check (const t_farm farm)
Checking the farm parameters for validity.
t_operations deposit (const t_farm farm, const MToken::t_amount damount, const bool doapprove)
Investing farm tokens in a farm by a user through a contract.
t_operations withdraw (const t_farm farm, const MToken::t_amount wamount)
Revocation of farm tokens by the user.
operation harvest (const t_farm farm)
Request a reward from the farm.
Detailed Description
Farm Interaction Module.
Definition at line 10 of file MFarm.ligo.
Member Enumeration Documentation
t_interface
enum MFarm::t_interface
Farm interfaces.
Enumerator
InterfaceCrunchy
Crunchy.
Farm methods:
Deposit to the farm - deposit(farmId, farmTokenAmount)
Withdrawal of a deposit from a farm - withdraw(farmId, farmTokenAmount)
Reward - harvest(farmId)
InterfaceQUIPU
Quipuswap farm.
Farm methods:
Deposit to the farm - deposit(farmId, farmTokenAmount, referrer option(address), rewards_receiver address, candidate key_hash)
Withdrawal of the deposit from the farm - withdraw(farmId, farmTokenAmount, receiver address, rewards_receiver address)
Reward - harvest(farmId, rewards_receiver address)
Definition at line 14 of file MFarm.ligo.
Member Function Documentation
check()
unit MFarm::check (const t_farm farm) inline
Checking the farm parameters for validity.
Definition at line 62 of file MFarm.ligo.
References MFarm::t_farm::addr, MFarmCrunchy::check(), MFarmQUIPU::check(), MToken::check(), MFarm::t_farm::farmToken, MFarm::t_farm::interface, InterfaceCrunchy, InterfaceQUIPU, and MFarm::t_farm::rewardToken.
Referenced by MPool::create().
deposit()
t_operations MFarm::deposit (const t_farm farm, const MToken::t_amount damount, const bool doapprove) inline
Investing farm tokens in a farm by a user through a contract.
Farm tokens from the user Tezos.sender are transferred first to the contract, and then to the farm
Definition at line 77 of file MFarm.ligo.
References MFarm::t_farm::addr, MToken::approve(), MToken::decline(), MFarmCrunchy::deposit(), MFarmQUIPU::deposit(), MFarm::t_farm::farmToken, MFarm::t_farm::id, MFarm::t_farm::interface, InterfaceCrunchy, InterfaceQUIPU, and MToken::transfer().
Referenced by MPool::deposit().
harvest()
operation MFarm::harvest (const t_farm farm) inline
Request a reward from the farm.
Reward tokens are transferred from the farm to the contract address
Definition at line 138 of file MFarm.ligo.
References MFarm::t_farm::addr, MFarmCrunchy::harvest(), MFarmQUIPU::harvest(), MFarm::t_farm::id, MFarm::t_farm::interface, InterfaceCrunchy, and InterfaceQUIPU.
Referenced by MPool::setPoolWinner().
withdraw()
t_operations MFarm::withdraw (const t_farm farm, const MToken::t_amount wamount) inline
Revocation of farm tokens by the user.
Farm tokens are transferred first to the contract, and then to the user at Tezos.sender
Definition at line 117 of file MFarm.ligo.
References MFarm::t_farm::addr, MFarm::t_farm::farmToken, MFarm::t_farm::id, MFarm::t_farm::interface, InterfaceCrunchy, InterfaceQUIPU, MToken::transfer(), MFarmCrunchy::withdraw(), and MFarmQUIPU::withdraw().
Referenced by MPool::withdraw().
The documentation for this class was generated from the following file:
MFarm.ligo