Pool Games: MAdmins Class Reference
MAdmins Class Reference
Contract admins management module.
Public Types
typedef address t_admin
Admin address.
typedef set< t_admin > t_admins
Set of admins.
Public Member Functions
bool isAdmin (const t_admins admins)
Is the current user an admin of the contract.
unit mustAdmin (const t_admins admins)
The current user must have the rights of the contract administrator.
t_admins forceAdd (const t_admin addadmin, t_admins admins)
Adding an admin is definitely.
t_admins forceRem (const t_admin remadmin, t_admins admins)
Removing the admin of course.
t_admins accessAdd (const t_admin addadmin, t_admins admins)
Adding an admin with admin rights verification.
t_admins accessRem (const t_admin remadmin, t_admins admins)
Admin removal with admin rights check.
Public Attributes
const string cERR_DENIED = "MAdmins/Denied"
Error: Access denied.
const string cERR_REM_LAST_ADMIN = "MAdmins/RemLastAdmin"
Error: Remove last admin.
const string cERR_NOT_FOUND = "MAdmins/NotFound"
Not found admin for remove.
Detailed Description
Contract admins management module.
Adding a new admin by any admin, removing any admin by any admin, including himself. The last admin cannot delete himself so that at least one admin remains in the contract. Example using a module without other access modules
#Include "module/MAdmins.ligo"
type t_storage record [
    admins: MAdmins.t_admins;
    ...
];
type t_entrypoint is
| AddAdmin of MAdmins.t_admin
| RemAdmin of MAdmins.t_admin
...
function main(const entrypoint: t_entrypoint; var s: t_storage): t_return is
case entrypoint of
| AddAdmin(params) -> (cNO_OPERATIONS, { s.admins := MAdmins.accessAdd(params, s.admins); } with s)
| RemAdmin(params) -> (cNO_OPERATIONS, { s.admins := MAdmins.accessRem(params, s.admins); } with s)
...
Definition at line 32 of file MAdmins.ligo.
Member Typedef Documentation
t_admin
typedef address MAdmins::t_admin
Admin address.
Definition at line 34 of file MAdmins.ligo.
t_admins
typedef set<t_admin> MAdmins::t_admins
Set of admins.
Definition at line 36 of file MAdmins.ligo.
Member Function Documentation
accessAdd()
t_admins MAdmins::accessAdd (const t_admin addadmin, t_admins admins) inline
Adding an admin with admin rights verification.
Definition at line 90 of file MAdmins.ligo.
References forceAdd(), and mustAdmin().
accessRem()
t_admins MAdmins::accessRem (const t_admin remadmin, t_admins admins) inline
Admin removal with admin rights check.
Definition at line 97 of file MAdmins.ligo.
References forceRem(), and mustAdmin().
forceAdd()
t_admins MAdmins::forceAdd (const t_admin addadmin, t_admins admins) inline
Adding an admin is definitely.
Checking the rights to add an admin should be done from the outside
Definition at line 63 of file MAdmins.ligo.
Referenced by accessAdd(), CPoolGames::main(), and CRandom::main().
forceRem()
t_admins MAdmins::forceRem (const t_admin remadmin, t_admins admins) inline
Removing the admin of course.
Checking the rights to delete the admin should be done from the outside You cannot delete an admin when there is only one left and there is no contract owner., which can add an admin, the error cERR_REM_LAST_ADMIN will be returned If the admin for deletion is not found, the error cERR_NOT_FOUND will be returned
Definition at line 77 of file MAdmins.ligo.
References cERR_NOT_FOUND, and cERR_REM_LAST_ADMIN.
Referenced by accessRem(), CPoolGames::main(), and CRandom::main().
isAdmin()
bool MAdmins::isAdmin (const t_admins admins) inline
Is the current user an admin of the contract.
Definition at line 44 of file MAdmins.ligo.
Referenced by mustAdmin().
mustAdmin()
unit MAdmins::mustAdmin (const t_admins admins) inline
The current user must have the rights of the contract administrator.
If the user is not an admin, the error cDENIED will be returned
Definition at line 52 of file MAdmins.ligo.
References cERR_DENIED, and isAdmin().
Referenced by accessAdd(), and accessRem().
Member Data Documentation
cERR_DENIED
const string MAdmins::cERR_DENIED = "MAdmins/Denied"
Error: Access denied.
Definition at line 38 of file MAdmins.ligo.
Referenced by mustAdmin().
cERR_NOT_FOUND
const string MAdmins::cERR_NOT_FOUND = "MAdmins/NotFound"
Not found admin for remove.
Definition at line 40 of file MAdmins.ligo.
Referenced by forceRem().
cERR_REM_LAST_ADMIN
const string MAdmins::cERR_REM_LAST_ADMIN = "MAdmins/RemLastAdmin"
Error: Remove last admin.
Definition at line 39 of file MAdmins.ligo.
Referenced by forceRem().
The documentation for this class was generated from the following file:
MAdmins.ligo