Pool Games: CPoolGames Class Reference
CPoolGames Class Reference
Contract for periodic reward draws on deposit pools in farms.
Classes
struct t_game
Parameters of the drawing game.
struct t_opts
Pool settings.
struct t_pool
A pool for periodic raffles of rewards.
struct t_pool_create
Data for creating a pool.
struct t_pool_edit
Pool editing data.
struct t_pool_info
Pool information issued when requesting pool information.
struct t_stat
Pool statistics.
struct t_storage
Contract storage.
struct t_user
User parameters in the pool.
Public Types
enum t_pool_state { PoolStateActive , PoolStatePause , PoolStateRemove }
Pool status.
enum t_algo { AlgoTime , AlgoTimeVol , AlgoEqual }
The algorithm of pool draws.
enum t_game_state {
GameStateActivating , GameStateActive , GameStateComplete , GameStateWaitRandom ,
GameStateWaitWinner , GameStatePause
}
States of the reward drawing game.
enum t_entrypoint {
ChangeOwner , ChangeAdmin , CreatePool , PausePool ,
StartPool , RemovePool , EditPool , SetPoolGameComplete ,
GetPoolRandom , SetPoolWinner , Deposit , Withdraw ,
WithdrawAll , OnRandom , OnBalanseFA1_2 , OnBalanseFA2 ,
AfterReward2Tez
}
All entrypoints of contract.
typedef pair< t_operations, t_storage > t_return
The returned result of the contract.
typedef nat t_weight
Weight to determine the probability of a participant winning.
typedef t_i t_ipool
Pool Index.
typedef big_map< t_ipool, t_pool > t_pools
Pools by their ID.
typedef pair< t_ipool, address > t_ipooladdr
The key for searching the user's index by pool index and address.
typedef big_map< t_ipooladdr, t_user > t_ipooladdr2user
Index in the pool by pool number and user address.
typedef pair< address, MToken::t_token > t_approve
The address that is allowed to debit tokens from the contract.
typedef big_map< t_approve, unit > t_approved
Already approved addresses for debiting tokens from the contract.
typedef pair< address, nat > t_farm_ident
Farm identification.
typedef big_map< t_farm_ident, unit > t_farms
Used farms.
Public Member Functions
bool isAdmin (const t_storage s)
Is Tezos.sender an admin of the contract?
unit mustAdmin (const t_storage s)
If Tezos.sender is not the contract admin, an error is generated.
unit mustAfter (const unit _)
Checking for self-call.
t_return main (const t_entrypoint entrypoint, t_storage s)
Single entry point of the contract.
Public Attributes
const compileTimeError cteAdminOrAdmins = "Compile time error: Must be ENABLE_ADMIN or ENABLE_ADMINS, not together"
Must be ENABLE_ADMIN or ENABLE_ADMINS, not together.
const compileTimeError cteOwnerOrAdmins = "Compile time error: Must be ENABLE_OWNER or ENABLE_ADMIN or ENABLE_ADMINS"
Must be ENABLE_OWNER or ENABLE_ADMIN or ENABLE_ADMINS.
const compileTimeError cteManagerForService = "Compile time error: Must be ENABLE_POOL_MANAGER, when ENABLE_POOL_AS_SERVICE"
Must be defined ENABLE_POOL_MANAGER, when ENABLE_POOL_AS_SERVICE.
const nat cMIN_GAME_SECONDS = 10n * 60n
Minimal seconds for game.
const nat cMAX_GAME_SECONDS = 10n * 86400n
Maximum seconds for game.
const string cERR_AFTER_DENIED = "After/Denied"
Error: The method should only be called by the contract itself.
Detailed Description
Contract for periodic reward draws on deposit pools in farms.
Todo:
Confirmation of the winner by other pool participants (except the winner) for a small reward from the winnings of the first N confirmed
The participants' choice of the token or XTZ in which they want to receive the winnings and autoconvert the winnings into the token needed by a particular user
According to the flag set by the user, the auto-investment of the won tokens into the same pool through auto-conversion
Receipt and withdrawal of remuneration by pool managers from the moment of suspension of the parties and until the withdrawal of all deposits by users
The start of the draw when making the first deposit to the pool
Definition at line 8 of file CPoolGames/access.ligo.
Member Typedef Documentation
t_approve
typedef pair<address,MToken::t_token> CPoolGames::t_approve
The address that is allowed to debit tokens from the contract.
Definition at line 569 of file CPoolGames/types.ligo.
t_approved
typedef big_map<t_approve,unit> CPoolGames::t_approved
Already approved addresses for debiting tokens from the contract.
Definition at line 573 of file CPoolGames/types.ligo.
t_farm_ident
typedef pair<address,nat> CPoolGames::t_farm_ident
Farm identification.
Definition at line 577 of file CPoolGames/types.ligo.
t_farms
typedef big_map<t_farm_ident,unit> CPoolGames::t_farms
Used farms.
Definition at line 581 of file CPoolGames/types.ligo.
t_ipool
typedef t_i CPoolGames::t_ipool
Pool Index.
Definition at line 492 of file CPoolGames/types.ligo.
t_ipooladdr
typedef pair<t_ipool,address> CPoolGames::t_ipooladdr
The key for searching the user's index by pool index and address.
Definition at line 540 of file CPoolGames/types.ligo.
t_ipooladdr2user
typedef big_map<t_ipooladdr,t_user> CPoolGames::t_ipooladdr2user
Index in the pool by pool number and user address.
Definition at line 544 of file CPoolGames/types.ligo.
t_pools
typedef big_map<t_ipool,t_pool> CPoolGames::t_pools
Pools by their ID.
Definition at line 493 of file CPoolGames/types.ligo.
t_return
typedef pair<t_operations,t_storage> CPoolGames::t_return
The returned result of the contract.
Definition at line 70 of file CPoolGames/storage.ligo.
t_weight
typedef nat CPoolGames::t_weight
Weight to determine the probability of a participant winning.
The probability of a user winning is proportional to the ratio of the participant's weight to the weight of the entire game
Definition at line 247 of file CPoolGames/types.ligo.
Member Enumeration Documentation
t_algo
enum CPoolGames::t_algo
The algorithm of pool draws.
In addition to the algorithm itself, in each case, additional settings minDeposit, minSeconds are used, maxDeposit (only for AlgoTimeVol) for additional restrictions
See also
t_opts.minDeposit, t_opts.minSeconds, t_opts.maxDeposit
Enumerator
AlgoTime
The probability of winning is proportional to the total time in the game.
The time of entry of each user into the draw is fixed. At the end of the game, all the time spent in the game of all users are summed up (and this sum is taken as probability 1.0). Next, a random number is normalized to this amount and the user is selected based on this number. As a result, the probability of a user winning is proportional to his time in the pool. Zeroing the deposit removes the user from the game, respectively, removes his time in the pool, this makes it pointless to exit and re-enter the game. This algorithm is more interesting for users with small deposits, the probability of winning does not depend on the size of the deposit, so you can invest little and win a lot.
See also
t_opts.minDeposit, t_opts.minSeconds, t_weight, t_game.weight
AlgoTimeVol
The probability of winning is proportional to the sum of the products of the volume for the time in the game.
The time of entry of each user into the draw and his deposit at this moment is fixed. When replenishing the deposit, the previous deposit is multiplied by its time of presence in the pool in seconds and this amount is accumulated separately for each user. This allows users to increase the probability of winning by increasing the deposit during the game. At the end of the game, all the time spent in the game multiplied by the deposits of all users are summed up (taking into account deposits during the game, see above) (and this amount is taken as probability 1.0). Next, a random number is normalized to this amount and the user is selected based on this number. As a result, the probability of a user winning is proportional to the sum of the products of his deposit and the time spent in his liquidity pool. Zeroing the deposit removes the user from the game, respectively, removes his time in the pool, this makes it pointless to exit and re-enter the game. This algorithm is more interesting for users with large deposits, the probability of winning depends on the size of the deposit, so you can significantly increase the probability of winning by investing a large deposit.
See also
t_opts.minDeposit, t_opts.maxDeposit, t_weight, t_game.weight
AlgoEqual
The probability of winning is equally likely.
The probability of winning is equally likely for all users in the pool who are present at the end of the game, all have a weight of 1. Using the algorithm without minSeconds is vulnerable to freeloaders who enter the pool only before the draw
See also
t_opts.minSeconds, t_weight, t_game.weight
Definition at line 57 of file CPoolGames/types.ligo.
t_entrypoint
enum CPoolGames::t_entrypoint
All entrypoints of contract.
Enumerator
ChangeOwner
Change owner of contract.
See also
MOwner, t_storage.owner
ChangeAdmin
Change admin of contract.
See also
MAdmin, t_storage.admin
CreatePool
Create new pool.
PausePool
Pause pool.
StartPool
Play pool (after pause)
RemovePool
Remove pool (after game)
EditPool
Edit pool (paused)
SetPoolGameComplete
Mark pool game complete by time.
Get random number from source
GetPoolRandom
SetPoolWinner
Set pool game winner.
Deposit
Deposit to pool.
Withdraw
Withdraw from pool.
WithdrawAll
Withdraw all from pool.
OnRandom
Callback with random number for detect winner.
OnBalanseFA1_2
Callback with balance of token FA1.2.
OnBalanseFA2
Callback with balance of token FA2.
AfterReward2Tez
Colback of himself after exchanging reward tokens for tokens for burning.
Definition at line 24 of file CPoolGames.ligo.
t_game_state
enum CPoolGames::t_game_state
States of the reward drawing game.
Enumerator
GameStateActivating
The game is being launched.
This state remains in the vault only when users make or withdraw a deposit after the end of the draw in an empty pool. Launching a new drawing requires additional operations, it will be incorrect to demand gas consumption for these operations from the user. A full game launch will be made later by the pool manager.
GameStateActive
There is a drawing game going on.
GameStateComplete
The drawing game is over in time.
GameStateWaitRandom
The drawing game is over in time, we are waiting for a random number to determine the winner.
GameStateWaitWinner
The drawing game is over in time, a random number has been received (or is not required), we are waiting for the winner to be determined by an external code.
GameStatePause
The games are suspended (the drawing game is completed, but the launch of the next one is blocked)
Definition at line 211 of file CPoolGames/types.ligo.
t_pool_state
enum CPoolGames::t_pool_state
Pool status.
Enumerator
PoolStateActive
The pool is active.
A reward is played periodically for all pool participants according to the pool settings
See also
StartPool, CreatePool
PoolStatePause
Pool suspended.
If the drawing game is active, it continues until completion, but the next one will not be started.
See also
PausePool, CreatePool
PoolStateRemove
Pool for deletion.
If the drawing game is active, it continues until the end. At the end of the game, when users have collected all deposits, the pool will be deleted during the last deposit debiting. If the pool is already empty at the time of setting the status, it will be deleted immediately.
See also
RemovePool
Definition at line 17 of file CPoolGames/types.ligo.
Member Function Documentation
isAdmin()
bool CPoolGames::isAdmin (const t_storage s) inline
Is Tezos.sender an admin of the contract?
Definition at line 24 of file CPoolGames/access.ligo.
References CPoolGames::t_storage::admin, MAdmin::isAdmin(), MOwner::isOwner(), and CPoolGames::t_storage::owner.
main()
t_return CPoolGames::main (const t_entrypoint entrypoint, t_storage s) inline
Single entry point of the contract.
Definition at line 141 of file CPoolGames.ligo.
References MOwner::accessChange(), CPoolGames::t_storage::admin, AfterReward2Tez, MPools::afterReward2Tez(), ChangeAdmin, ChangeOwner, MPools::changePoolManager(), cNO_OPERATIONS, CreatePool, MPools::createPool(), Deposit, MPools::deposit(), EditPool, MPools::editPool(), ENABLE_ADMIN, ENABLE_ADMINS, MAdmins::forceAdd(), MAdmins::forceRem(), GetPoolRandom, MPools::getPoolRandom(), mustAdmin(), mustAfter(), MPools::onBalanceFA1_2(), MPools::onBalanceFA2(), OnBalanseFA1_2, OnBalanseFA2, OnRandom, MPools::onRandom(), CPoolGames::t_storage::owner, PausePool, MPools::pausePool(), RemovePool, MPools::removePool(), SetPoolGameComplete, MPools::setPoolGameComplete(), SetPoolWinner, MPools::setPoolWinner(), StartPool, MPools::startPool(), Withdraw, MPools::withdraw(), and WithdrawAll.
mustAdmin()
unit CPoolGames::mustAdmin (const t_storage s) inline
If Tezos.sender is not the contract admin, an error is generated.
Definition at line 36 of file CPoolGames/access.ligo.
References CPoolGames::t_storage::admin, MOwner::isOwner(), MAdmin::mustAdmin(), and CPoolGames::t_storage::owner.
Referenced by main().
mustAfter()
unit CPoolGames::mustAfter (const unit _) inline
Checking for self-call.
Definition at line 134 of file CPoolGames.ligo.
References cERR_AFTER_DENIED.
Referenced by main().
Member Data Documentation
cERR_AFTER_DENIED
const string CPoolGames::cERR_AFTER_DENIED = "After/Denied"
Error: The method should only be called by the contract itself.
Definition at line 130 of file CPoolGames.ligo.
Referenced by mustAfter().
cMAX_GAME_SECONDS
const nat CPoolGames::cMAX_GAME_SECONDS = 10n * 86400n
Maximum seconds for game.
Definition at line 101 of file CPoolGames/config.ligo.
cMIN_GAME_SECONDS
const nat CPoolGames::cMIN_GAME_SECONDS = 10n * 60n
Minimal seconds for game.
Definition at line 100 of file CPoolGames/config.ligo.
cteAdminOrAdmins
const compileTimeError CPoolGames::cteAdminOrAdmins = "Compile time error: Must be ENABLE_ADMIN or ENABLE_ADMINS, not together"
Must be ENABLE_ADMIN or ENABLE_ADMINS, not together.
Definition at line 41 of file CPoolGames/config.ligo.
cteManagerForService
const compileTimeError CPoolGames::cteManagerForService = "Compile time error: Must be ENABLE_POOL_MANAGER, when ENABLE_POOL_AS_SERVICE"
Must be defined ENABLE_POOL_MANAGER, when ENABLE_POOL_AS_SERVICE.
Definition at line 81 of file CPoolGames/config.ligo.
cteOwnerOrAdmins
const compileTimeError CPoolGames::cteOwnerOrAdmins = "Compile time error: Must be ENABLE_OWNER or ENABLE_ADMIN or ENABLE_ADMINS"
Must be ENABLE_OWNER or ENABLE_ADMIN or ENABLE_ADMINS.
Definition at line 47 of file CPoolGames/config.ligo.
The documentation for this class was generated from the following files:
CPoolGames/access.ligo
CPoolGames/storage.ligo
CPoolGames/types.ligo
CPoolGames/config.ligo
CPoolGames.ligo