Pool Games: MToken Class Reference
MToken Class Reference
Module for working with tokens of different standards.
Classes
struct t_token
Token.
Public Types
typedef nat t_amount
Number of tokens.
typedef FA2 t_fa
Token standards FA2, FA1.2.
Public Member Functions
unit check (const t_token token)
Checking the token parameters for validity.
bool isEqual (const t_token token0, const t_token token1)
Comparison of tokens.
operation transfer (const t_token token, const address src, const address dst, const t_amount tamount)
Transfer of tokens.
operation balanceOf (const t_token token, const address owner, const MFA1_2::t_balance_callback callbackFA1_2, const MFA2::t_balance_callback callbackFA2)
Request for a token balance.
operation approve (const t_token token, const address operator,const t_amount tamount)
Approval of Token Disposal.
operation decline (const t_token token, const address operator)
Prohibition of token disposal.
operation burn (const t_token token, const address src, const t_amount bamount)
Burning tokens.
Public Attributes
FA1_2
Detailed Description
Module for working with tokens of different standards.
Definition at line 9 of file MToken.ligo.
Member Typedef Documentation
t_amount
typedef nat MToken::t_amount
Number of tokens.
Definition at line 11 of file MToken.ligo.
t_fa
typedef FA2 MToken::t_fa
Token standards FA2, FA1.2.
Definition at line 14 of file MToken.ligo.
Member Function Documentation
approve()
operation MToken::approve (const t_token token, const address operator, const t_amount tamount) inline
Approval of Token Disposal.
Definition at line 56 of file MToken.ligo.
References MToken::t_token::addr, MFA1_2::approve(), MFA2::approve(), MToken::t_token::fa, FA1_2, and MToken::t_token::token_id.
Referenced by MFarm::deposit().
balanceOf()
operation MToken::balanceOf (const t_token token, const address owner, const MFA1_2::t_balance_callback callbackFA1_2, const MFA2::t_balance_callback callbackFA2) inline
Request for a token balance.
Definition at line 48 of file MToken.ligo.
References MToken::t_token::addr, MFA1_2::balanceOf(), MFA2::balanceOf(), MToken::t_token::fa, FA1_2, and MToken::t_token::token_id.
Referenced by MPool::afterReward2Tez(), and MPool::setPoolWinner().
burn()
operation MToken::burn (const t_token token, const address src, const t_amount bamount) inline
Burning tokens.
Definition at line 72 of file MToken.ligo.
References MToken::t_token::addr, cZERO_ADDRESS, MToken::t_token::fa, FA1_2, MToken::t_token::token_id, MFA1_2::transfer(), and MFA2::transfer().
Referenced by MPool::onBalanceAfterHarvest(), and MPool::onBalanceAfterTez2Burn().
check()
unit MToken::check (const t_token token) inline
Checking the token parameters for validity.
Definition at line 26 of file MToken.ligo.
References MToken::t_token::addr, MFA1_2::check(), MFA2::check(), MToken::t_token::fa, and FA1_2.
Referenced by MFarm::check(), and MPool::checkBurn().
decline()
operation MToken::decline (const t_token token, const address operator) inline
Prohibition of token disposal.
Definition at line 64 of file MToken.ligo.
References MToken::t_token::addr, MFA1_2::decline(), MFA2::decline(), MToken::t_token::fa, FA1_2, and MToken::t_token::token_id.
Referenced by MFarm::deposit().
isEqual()
bool MToken::isEqual (const t_token token0, const t_token token1) inline
Comparison of tokens.
Definition at line 35 of file MToken.ligo.
References MToken::t_token::addr, MToken::t_token::fa, and MToken::t_token::token_id.
Referenced by MPool::checkBurn(), and MPool::onBalanceAfterHarvest().
transfer()
operation MToken::transfer (const t_token token, const address src, const address dst, const t_amount tamount) inline
Transfer of tokens.
Definition at line 40 of file MToken.ligo.
References MToken::t_token::addr, MToken::t_token::fa, FA1_2, MToken::t_token::token_id, MFA1_2::transfer(), and MFA2::transfer().
Referenced by MFarm::deposit(), MPool::onBalanceAfterHarvest(), and MFarm::withdraw().
Member Data Documentation
FA1_2
MToken::FA1_2
Definition at line 14 of file MToken.ligo.
Referenced by approve(), balanceOf(), burn(), check(), decline(), and transfer().
The documentation for this class was generated from the following file:
MToken.ligo