Pool Games: MOwner Class Reference
MOwner Class Reference
Contract owner management module.
Public Types
typedef address t_owner
Contract owner.
Public Member Functions
bool isOwner (const t_owner owner)
Is the current user the owner.
unit mustOwner (const t_owner owner)
The current user must have the rights of the owner.
t_owner accessChange (const t_owner newowner, t_owner owner)
Change of owner with verification of the owner's rights.
Public Attributes
const string cERR_DENIED = "MOwner/Denied"
Error: Access denied.
Detailed Description
Contract owner management module.
The owner can replace the owner with another Example using a module without other access modules
#Include "module/MOwner.ligo"
type t_storage record [
    owner: MOwner.t_owner;
    ...
];
type t_entrypoint is
| ChangeOwner of MOwner.t_owner
...
function main(const entrypoint: t_entrypoint; var s: t_storage): t_return is
case entrypoint of
| ChangeOwner(params) -> (cNO_OPERATIONS, { s.owner:= MOwner.accessChange(params, s.owner); } with s)
...
Definition at line 28 of file MOwner.ligo.
Member Typedef Documentation
t_owner
typedef address MOwner::t_owner
Contract owner.
Definition at line 30 of file MOwner.ligo.
Member Function Documentation
accessChange()
t_owner MOwner::accessChange (const t_owner newowner, t_owner owner) inline
Change of owner with verification of the owner's rights.
Definition at line 51 of file MOwner.ligo.
References mustOwner().
Referenced by CPoolGames::main(), and CRandom::main().
isOwner()
bool MOwner::isOwner (const t_owner owner) inline
Is the current user the owner.
Definition at line 36 of file MOwner.ligo.
Referenced by CPoolGames::isAdmin(), CPoolGames::mustAdmin(), and mustOwner().
mustOwner()
unit MOwner::mustOwner (const t_owner owner) inline
The current user must have the rights of the owner.
If the user is not the owner, the error cERR_DENIED will be returned
Definition at line 44 of file MOwner.ligo.
References cERR_DENIED, and isOwner().
Referenced by accessChange().
Member Data Documentation
cERR_DENIED
const string MOwner::cERR_DENIED = "MOwner/Denied"
Error: Access denied.
Definition at line 32 of file MOwner.ligo.
Referenced by mustOwner().
The documentation for this class was generated from the following file:
MOwner.ligo