Pool Games: MFarmQUIPU Class Reference
MFarmQUIPU Class Reference
QUIPU Farm Interaction Module.
Classes
struct t_deposit_params
Parameters for the deposit to the QUIPU farm.
struct t_harvest_params
Parameters for receiving rewards from the QUIPU farm.
struct t_withdraw_params
Parameters for extracting a deposit to the QUIPU farm.
Public Types
typedef nat t_farm_id
QUIPU farm ID.
typedef QUIPUDeposit of t_deposit_params t_deposit_method
Prototype of the deposit method of the QUIPU farm.
typedef contract< t_deposit_method > t_deposit_contract
Contract with deposit entry point in QUIPU farm format.
typedef QUIPUWithdraw of t_withdraw_params t_withdraw_method
Prototype of the QUIPU farm withdrawal method.
typedef contract< t_withdraw_method > t_withdraw_contract
Contract with withdrawal entry point in QUIPU farm format.
typedef QUIPUHarvest of t_harvest_params t_harvest_method
Prototype of the QUIPU farm harvest method.
typedef contract< t_harvest_method > t_harvest_contract
A contract with the harvest entry point in the QUIPU farm format.
Public Member Functions
t_deposit_contract depositEntrypoint (const address addr)
Get the deposit farm entry point with the QUIPU interface.
t_deposit_method depositParams (const t_farm_id farm_id, const MToken::t_amount damount)
Parameters for the deposit QUIPU method.
operation deposit (const address addr, const t_farm_id farm_id, const MToken::t_amount damount)
Deposit to QUIPU farm.
t_withdraw_contract withdrawEntrypoint (const address addr)
Get a farm withdrawal entry point with the QUIPU interface.
t_withdraw_method withdrawParams (const t_farm_id farm_id, const MToken::t_amount wamount)
Parameters for the deposit QUIPU method.
operation withdraw (const address addr, const t_farm_id farm_id, const MToken::t_amount wamount)
Extracting a deposit from a QUIPU farm.
t_harvest_contract harvestEntrypoint (const address addr)
Get the harvest farm entry point with the QUIPU interface.
t_harvest_method harvestParams (const t_farm_id farm_id)
Parameters for the harvest QUIPU method.
operation harvest (const address addr, const t_farm_id farm_id)
Getting Rewards from QUIPU farm.
unit check (const address addr)
Checking the farm parameters for validity.
Public Attributes
const string cERR_NOT_FOUND_DEPOSIT = "MFarmQUIPU/NotFoundDeposit"
Error: The deposit entry point for the farm in QUIPU format was not found.
const string cERR_NOT_FOUND_WITHDRAW = "MFarmQUIPU/NotFoundWithdraw"
Error: No withdrawal entry point found for the farm in QUIPU format.
const string cERR_NOT_FOUND_HARVEST = "MFarmQUIPU/NotFoundHarvest"
Error: The harvest entry point for the farm in QUIPU format was not found.
Detailed Description
QUIPU Farm Interaction Module.
Definition at line 8 of file MFarmQUIPU.ligo.
Member Typedef Documentation
t_deposit_contract
typedef contract<t_deposit_method> MFarmQUIPU::t_deposit_contract
Contract with deposit entry point in QUIPU farm format.
Definition at line 40 of file MFarmQUIPU.ligo.
t_deposit_method
typedef QUIPUDeposit of t_deposit_params MFarmQUIPU::t_deposit_method
Prototype of the deposit method of the QUIPU farm.
Definition at line 36 of file MFarmQUIPU.ligo.
t_farm_id
typedef nat MFarmQUIPU::t_farm_id
QUIPU farm ID.
Definition at line 22 of file MFarmQUIPU.ligo.
t_harvest_contract
typedef contract<t_harvest_method> MFarmQUIPU::t_harvest_contract
A contract with the harvest entry point in the QUIPU farm format.
Definition at line 72 of file MFarmQUIPU.ligo.
t_harvest_method
typedef QUIPUHarvest of t_harvest_params MFarmQUIPU::t_harvest_method
Prototype of the QUIPU farm harvest method.
Definition at line 68 of file MFarmQUIPU.ligo.
t_withdraw_contract
typedef contract<t_withdraw_method> MFarmQUIPU::t_withdraw_contract
Contract with withdrawal entry point in QUIPU farm format.
Definition at line 57 of file MFarmQUIPU.ligo.
t_withdraw_method
typedef QUIPUWithdraw of t_withdraw_params MFarmQUIPU::t_withdraw_method
Prototype of the QUIPU farm withdrawal method.
Definition at line 53 of file MFarmQUIPU.ligo.
Member Function Documentation
check()
unit MFarmQUIPU::check (const address addr) inline
Checking the farm parameters for validity.
Definition at line 156 of file MFarmQUIPU.ligo.
References depositEntrypoint(), harvestEntrypoint(), and withdrawEntrypoint().
Referenced by MFarm::check().
deposit()
operation MFarmQUIPU::deposit (const address addr, const t_farm_id farm_id, const MToken::t_amount damount) inline
Deposit to QUIPU farm.
Definition at line 95 of file MFarmQUIPU.ligo.
References depositEntrypoint(), and depositParams().
Referenced by MFarm::deposit().
depositEntrypoint()
t_deposit_contract MFarmQUIPU::depositEntrypoint (const address addr) inline
Get the deposit farm entry point with the QUIPU interface.
Definition at line 76 of file MFarmQUIPU.ligo.
References cERR_NOT_FOUND_DEPOSIT.
Referenced by check(), and deposit().
depositParams()
t_deposit_method MFarmQUIPU::depositParams (const t_farm_id farm_id, const MToken::t_amount damount) inline
Parameters for the deposit QUIPU method.
Definition at line 84 of file MFarmQUIPU.ligo.
References cZERO_KEY_HASH.
Referenced by deposit().
harvest()
operation MFarmQUIPU::harvest (const address addr, const t_farm_id farm_id) inline
Getting Rewards from QUIPU farm.
Definition at line 147 of file MFarmQUIPU.ligo.
References harvestEntrypoint(), and harvestParams().
Referenced by MFarm::harvest().
harvestEntrypoint()
t_harvest_contract MFarmQUIPU::harvestEntrypoint (const address addr) inline
Get the harvest farm entry point with the QUIPU interface.
Definition at line 131 of file MFarmQUIPU.ligo.
References cERR_NOT_FOUND_HARVEST.
Referenced by check(), and harvest().
harvestParams()
t_harvest_method MFarmQUIPU::harvestParams (const t_farm_id farm_id) inline
Parameters for the harvest QUIPU method.
Definition at line 139 of file MFarmQUIPU.ligo.
Referenced by harvest().
withdraw()
operation MFarmQUIPU::withdraw (const address addr, const t_farm_id farm_id, const MToken::t_amount wamount) inline
Extracting a deposit from a QUIPU farm.
Definition at line 122 of file MFarmQUIPU.ligo.
References withdrawEntrypoint(), and withdrawParams().
Referenced by MFarm::withdraw().
withdrawEntrypoint()
t_withdraw_contract MFarmQUIPU::withdrawEntrypoint (const address addr) inline
Get a farm withdrawal entry point with the QUIPU interface.
Definition at line 104 of file MFarmQUIPU.ligo.
References cERR_NOT_FOUND_WITHDRAW.
Referenced by check(), and withdraw().
withdrawParams()
t_withdraw_method MFarmQUIPU::withdrawParams (const t_farm_id farm_id, const MToken::t_amount wamount) inline
Parameters for the deposit QUIPU method.
Definition at line 112 of file MFarmQUIPU.ligo.
Referenced by withdraw().
Member Data Documentation
cERR_NOT_FOUND_DEPOSIT
const string MFarmQUIPU::cERR_NOT_FOUND_DEPOSIT = "MFarmQUIPU/NotFoundDeposit"
Error: The deposit entry point for the farm in QUIPU format was not found.
Definition at line 12 of file MFarmQUIPU.ligo.
Referenced by depositEntrypoint().
cERR_NOT_FOUND_HARVEST
const string MFarmQUIPU::cERR_NOT_FOUND_HARVEST = "MFarmQUIPU/NotFoundHarvest"
Error: The harvest entry point for the farm in QUIPU format was not found.
Definition at line 20 of file MFarmQUIPU.ligo.
Referenced by harvestEntrypoint().
cERR_NOT_FOUND_WITHDRAW
const string MFarmQUIPU::cERR_NOT_FOUND_WITHDRAW = "MFarmQUIPU/NotFoundWithdraw"
Error: No withdrawal entry point found for the farm in QUIPU format.
Definition at line 16 of file MFarmQUIPU.ligo.
Referenced by withdrawEntrypoint().
The documentation for this class was generated from the following file:
MFarmQUIPU.ligo