Pool Games: MPoolGame Class Reference
MPoolGame Class Reference
The module of the reward drawing game.
Public Member Functions
t_game create (const t_game_state state, const nat seconds)
Game parameters when creating a pool in an active or suspended state.
t_pool newGame (t_pool pool)
Start a new game.
pair< t_pool, t_user > onDeposit (t_pool pool, t_user user, const MToken::t_amount damount)
The deposit has been replenished by the user.
pair< t_pool, t_user > onWithdraw (t_pool pool, t_user user, const MToken::t_amount wamount)
The deposit was extracted by the user.
t_pool checkComplete (t_pool pool)
We check if the time of the draw has not ended.
Detailed Description
The module of the reward drawing game.
Definition at line 6 of file MPoolGame.ligo.
Member Function Documentation
checkComplete()
t_pool MPoolGame::checkComplete (t_pool pool) inline
We check if the time of the draw has not ended.
Definition at line 166 of file MPoolGame.ligo.
Referenced by MPool::deposit(), MPool::setGameComplete(), and MPool::withdraw().
create()
t_game MPoolGame::create (const t_game_state state, const nat seconds) inline
Game parameters when creating a pool in an active or suspended state.
Definition at line 10 of file MPoolGame.ligo.
References cZERO_ADDRESS.
Referenced by MPool::create().
newGame()
t_pool MPoolGame::newGame (t_pool pool) inline
Start a new game.
Definition at line 29 of file MPoolGame.ligo.
Referenced by MPool::newGame().
onDeposit()
pair<t_pool,t_user> MPoolGame::onDeposit (t_pool pool, t_user user, const MToken::t_amount damount) inline
The deposit has been replenished by the user.
Definition at line 46 of file MPoolGame.ligo.
Referenced by MPool::deposit().
onWithdraw()
pair<t_pool,t_user> MPoolGame::onWithdraw (t_pool pool, t_user user, const MToken::t_amount wamount) inline
The deposit was extracted by the user.
Definition at line 95 of file MPoolGame.ligo.
Referenced by MPool::withdraw().
The documentation for this class was generated from the following file:
MPoolGame.ligo