Pool Games: MFA2 Class Reference
MFA2 Class Reference
Types and methods for FA2.
Classes
struct t_balance_params
Balance requests and callback for returning responses.
struct t_balance_request
Balance Request.
struct t_balance_response
Response to the balance request.
struct t_operator
One operator.
struct t_transfer_dst
One destination for the transfer of tokens.
struct t_transfer_src2dsts
List of transfers from one address.
Public Types
typedef nat t_token_id
Token ID.
typedef list< t_transfer_src2dsts > t_transfer_params
List of transfers from different addresses.
typedef FA2Transfer of t_transfer_params t_transfer_method
Prototype of the transfer method.
typedef contract< t_transfer_method > t_transfer_contract
Contract with the transfer entry point.
typedef list< t_balance_response > t_balance_callback_params
Balance Callback Parameters.
typedef contract< t_balance_callback_params > t_balance_callback
Type of callback for balance request.
typedef FA2Balance of t_balance_params t_balance_method
Prototype of the balance method.
typedef contract< t_balance_method > t_balance_contract
Contract with the balance_of entry point.
typedef Add_operator of t_operator t_operators_case
Prototypes of operators.
typedef list< t_operators_case > t_operators_params
Parameters of the update_operators method.
typedef FA2Operators of t_operators_params t_operators_method
Prototype of the update_operators method.
typedef contract< t_operators_method > t_operators_contract
Contract with the update_operators entry point.
Public Member Functions
t_transfer_contract transferEntrypoint (const address addr)
Get the transfer token entry point.
t_transfer_method transferParams (const t_token_id token_id, const address src, const address dst, const nat tamount)
Parameters for transferring tokens.
operation transfer (const address token, const t_token_id token_id, const address src, const address dst, const nat tamount)
Token Transfer Operation.
t_balance_contract balanceEntrypoint (const address addr)
Get the entry point of the balance_of token.
t_balance_method balanceParams (const t_token_id token_id, const address owner, const t_balance_callback callback)
Parameters for requesting a token balance.
operation balanceOf (const address token, const t_token_id token_id, const address owner, const t_balance_callback callback)
Request for a token balance.
t_operators_contract operatorsEntrypoint (const address addr)
Get the token's update_operators entry point.
t_operators_method approveParams (const t_token_id token_id, const address operator)
Parameters for approving the disposal of tokens.
operation approve (const address token, const t_token_id token_id, const address operator)
The operation of approving the disposal of tokens.
t_operators_method declineParams (const t_token_id token_id, const address operator)
Parameters for prohibiting the disposal of tokens.
operation decline (const address token, const t_token_id token_id, const address operator)
The operation of prohibiting the disposal of tokens.
unit check (const address token)
Checking for compliance with the FA2 standard.
Public Attributes
Remove_operator of t_operator
const string cERR_NOT_FOUND_TRANSFER = "MFA2/NotFoundTransfer"
Error: The token transfer method was not found.
const string cERR_NOT_FOUND_BALANCEOF = "MFA2/NotFoundBalanceOf"
Error: The token's balance_of method was not found.
const string cERR_NOT_FOUND_OPERATORS = "MFA2/NotFoundUpdateOperators"
Error: Token update_operators method not found.
Detailed Description
Types and methods for FA2.
Definition at line 6 of file MFA2.ligo.
Member Typedef Documentation
t_balance_callback
typedef contract<t_balance_callback_params> MFA2::t_balance_callback
Type of callback for balance request.
Definition at line 62 of file MFA2.ligo.
t_balance_callback_params
typedef list<t_balance_response> MFA2::t_balance_callback_params
Balance Callback Parameters.
Definition at line 58 of file MFA2.ligo.
t_balance_contract
typedef contract<t_balance_method> MFA2::t_balance_contract
Contract with the balance_of entry point.
Definition at line 79 of file MFA2.ligo.
t_balance_method
typedef FA2Balance of t_balance_params MFA2::t_balance_method
Prototype of the balance method.
Definition at line 75 of file MFA2.ligo.
t_operators_case
typedef Add_operator of t_operator MFA2::t_operators_case
Prototypes of operators.
Definition at line 94 of file MFA2.ligo.
t_operators_contract
typedef contract<t_operators_method> MFA2::t_operators_contract
Contract with the update_operators entry point.
Definition at line 106 of file MFA2.ligo.
t_operators_method
typedef FA2Operators of t_operators_params MFA2::t_operators_method
Prototype of the update_operators method.
Definition at line 102 of file MFA2.ligo.
t_operators_params
typedef list<t_operators_case> MFA2::t_operators_params
Parameters of the update_operators method.
Definition at line 98 of file MFA2.ligo.
t_token_id
typedef nat MFA2::t_token_id
Token ID.
Definition at line 9 of file MFA2.ligo.
t_transfer_contract
typedef contract<t_transfer_method> MFA2::t_transfer_contract
Contract with the transfer entry point.
Definition at line 36 of file MFA2.ligo.
t_transfer_method
typedef FA2Transfer of t_transfer_params MFA2::t_transfer_method
Prototype of the transfer method.
Definition at line 32 of file MFA2.ligo.
t_transfer_params
typedef list<t_transfer_src2dsts> MFA2::t_transfer_params
List of transfers from different addresses.
Definition at line 28 of file MFA2.ligo.
Member Function Documentation
approve()
operation MFA2::approve (const address token, const t_token_id token_id, const address operator) inline
The operation of approving the disposal of tokens.
Definition at line 196 of file MFA2.ligo.
References approveParams(), and operatorsEntrypoint().
Referenced by MToken::approve().
approveParams()
t_operators_method MFA2::approveParams (const t_token_id token_id, const address operator) inline
Parameters for approving the disposal of tokens.
Definition at line 185 of file MFA2.ligo.
Referenced by approve().
balanceEntrypoint()
t_balance_contract MFA2::balanceEntrypoint (const address addr) inline
Get the entry point of the balance_of token.
Definition at line 147 of file MFA2.ligo.
References cERR_NOT_FOUND_BALANCEOF.
Referenced by balanceOf(), and check().
balanceOf()
operation MFA2::balanceOf (const address token, const t_token_id token_id, const address owner, const t_balance_callback callback) inline
Request for a token balance.
Definition at line 168 of file MFA2.ligo.
References balanceEntrypoint(), and balanceParams().
Referenced by MToken::balanceOf().
balanceParams()
t_balance_method MFA2::balanceParams (const t_token_id token_id, const address owner, const t_balance_callback callback) inline
Parameters for requesting a token balance.
Definition at line 155 of file MFA2.ligo.
Referenced by balanceOf().
check()
unit MFA2::check (const address token) inline
Checking for compliance with the FA2 standard.
Definition at line 226 of file MFA2.ligo.
References balanceEntrypoint(), operatorsEntrypoint(), and transferEntrypoint().
Referenced by MToken::check().
decline()
operation MFA2::decline (const address token, const t_token_id token_id, const address operator) inline
The operation of prohibiting the disposal of tokens.
Definition at line 216 of file MFA2.ligo.
References declineParams(), and operatorsEntrypoint().
Referenced by MToken::decline().
declineParams()
t_operators_method MFA2::declineParams (const t_token_id token_id, const address operator) inline
Parameters for prohibiting the disposal of tokens.
Definition at line 205 of file MFA2.ligo.
Referenced by decline().
operatorsEntrypoint()
t_operators_contract MFA2::operatorsEntrypoint (const address addr) inline
Get the token's update_operators entry point.
Definition at line 177 of file MFA2.ligo.
References cERR_NOT_FOUND_OPERATORS.
Referenced by approve(), check(), and decline().
transfer()
operation MFA2::transfer (const address token, const t_token_id token_id, const address src, const address dst, const nat tamount) inline
Token Transfer Operation.
Definition at line 138 of file MFA2.ligo.
References transferEntrypoint(), and transferParams().
Referenced by MToken::burn(), and MToken::transfer().
transferEntrypoint()
t_transfer_contract MFA2::transferEntrypoint (const address addr) inline
Get the transfer token entry point.
Definition at line 114 of file MFA2.ligo.
References cERR_NOT_FOUND_TRANSFER.
Referenced by check(), and transfer().
transferParams()
t_transfer_method MFA2::transferParams (const t_token_id token_id, const address src, const address dst, const nat tamount) inline
Parameters for transferring tokens.
Definition at line 122 of file MFA2.ligo.
Referenced by transfer().
Member Data Documentation
cERR_NOT_FOUND_BALANCEOF
const string MFA2::cERR_NOT_FOUND_BALANCEOF = "MFA2/NotFoundBalanceOf"
Error: The token's balance_of method was not found.
Definition at line 109 of file MFA2.ligo.
Referenced by balanceEntrypoint().
cERR_NOT_FOUND_OPERATORS
const string MFA2::cERR_NOT_FOUND_OPERATORS = "MFA2/NotFoundUpdateOperators"
Error: Token update_operators method not found.
Definition at line 110 of file MFA2.ligo.
Referenced by operatorsEntrypoint().
cERR_NOT_FOUND_TRANSFER
const string MFA2::cERR_NOT_FOUND_TRANSFER = "MFA2/NotFoundTransfer"
Error: The token transfer method was not found.
Definition at line 108 of file MFA2.ligo.
Referenced by transferEntrypoint().
t_operator
Remove_operator of MFA2::t_operator
Definition at line 94 of file MFA2.ligo.
The documentation for this class was generated from the following file:
MFA2.ligo