Pool Games: MPools Class Reference
MPools Class Reference
Module of the list of liquidity pools with periodic raffles of rewards.
Public Member Functions
t_pool getPool (const t_storage s, const t_ipool ipool)
Get a pool by index.
t_storage setPool (t_storage s, const t_ipool ipool, const t_pool pool)
Update the pool by index.
t_user getUser (const t_storage s, const t_ipool ipool)
Get the current user parameters in the pool.
t_storage setUser (t_storage s, const t_ipool ipool, const t_user user)
Update the current user parameters in the pool.
t_storage setPoolState (t_storage s, const t_ipool ipool, const t_pool_state state)
Set the pool state.
t_storage doRemovePool (t_storage s, const t_ipool ipool, const t_pool pool)
t_storage createPool (t_storage s, const t_pool_create pool_create)
Create new pool.
t_storage pausePool (const t_storage s, const t_ipool ipool)
Pause pool.
t_storage startPool (const t_storage s, const t_ipool ipool)
Play pool (after pause)
t_storage removePool (t_storage s, const t_ipool ipool)
Remove pool (after game)
t_storage editPool (t_storage s, const t_ipool ipool, const t_pool_edit pool_edit)
Edit pool (paused)
t_storage changePoolManager (t_storage s, const t_ipool ipool, const address newmanager)
Changing the pool manager.
t_return setPoolGameComplete (t_storage s, const t_ipool ipool)
Mark pool game complete by time.
t_return getPoolRandom (t_storage s, const t_ipool ipool)
Get random number from source.
t_return setPoolWinner (t_storage s, const t_ipool ipool, const address winner)
Set pool game winner.
t_return deposit (t_storage s, const t_ipool ipool, const MToken::t_amount damount)
Deposit to pool.
t_return withdraw (t_storage s, const t_ipool ipool, const MToken::t_amount wamount)
Withdraw from pool.
t_return onRandom (t_storage s, const t_ipool ipool, const MRandom::t_random random)
Callback with random number for detect winner.
t_return onBalance (t_storage s, const MToken::t_amount currentBalance)
Processing a callback with a balance.
t_return onBalanceFA1_2 (t_storage s, const MFA1_2::t_balance_callback_params currentBalance)
Callback with the FA1.2 token balance.
t_return onBalanceFA2 (t_storage s, const MFA2::t_balance_callback_params params)
Callback with FA2 token balance.
t_return afterReward2Tez (t_storage s, const t_ipool ipool)
Callback of himself after exchanging reward tokens for tez.
t_pool_info viewPoolInfo (const t_storage s, const t_ipool ipool)
Getting basic Pool information.
nat viewBalance (const t_storage s, const t_ipool ipool)
Getting the user's balance in the pool.
Public Attributes
const string cERR_NOT_FOUND = "MPools/NotFound"
Error: Pool not found.
const string cERR_FARM_USED = "MPools/FarmUsed"
Error: You cannot use the same farms in pools.
balance
Detailed Description
Module of the list of liquidity pools with periodic raffles of rewards.
Definition at line 8 of file MPools.ligo.
Member Function Documentation
afterReward2Tez()
t_return MPools::afterReward2Tez (t_storage s, const t_ipool ipool) inline
Callback of himself after exchanging reward tokens for tez.
Definition at line 260 of file MPools.ligo.
References MPool::afterReward2Tez(), getPool(), and setPool().
Referenced by CPoolGames::main().
changePoolManager()
t_storage MPools::changePoolManager (t_storage s, const t_ipool ipool, const address newmanager) inline
Changing the pool manager.
Definition at line 121 of file MPools.ligo.
References MPool::forceChangeManager(), getPool(), MPool::mustManager(), and setPool().
Referenced by CPoolGames::main().
createPool()
t_storage MPools::createPool (t_storage s, const t_pool_create pool_create) inline
Create new pool.
Definition at line 87 of file MPools.ligo.
References cERR_FARM_USED, and MPool::create().
Referenced by CPoolGames::main().
deposit()
t_return MPools::deposit (t_storage s, const t_ipool ipool, const MToken::t_amount damount) inline
Deposit to pool.
Definition at line 160 of file MPools.ligo.
References MPool::deposit(), getPool(), getUser(), setPool(), and setUser().
Referenced by CPoolGames::main().
doRemovePool()
t_storage MPools::doRemovePool (t_storage s, const t_ipool ipool, const t_pool pool) inline
Definition at line 78 of file MPools.ligo.
Referenced by removePool(), and withdraw().
editPool()
t_storage MPools::editPool (t_storage s, const t_ipool ipool, const t_pool_edit pool_edit) inline
Edit pool (paused)
Definition at line 112 of file MPools.ligo.
References MPool::edit(), getPool(), MPool::mustManager(), and setPool().
Referenced by CPoolGames::main().
getPool()
t_pool MPools::getPool (const t_storage s, const t_ipool ipool) inline
Get a pool by index.
If the pool is not found, the error cERR_NOT_FOUND will be returned
Definition at line 24 of file MPools.ligo.
References cERR_NOT_FOUND.
Referenced by afterReward2Tez(), changePoolManager(), deposit(), editPool(), getPoolRandom(), onBalance(), onRandom(), removePool(), setPoolGameComplete(), setPoolState(), setPoolWinner(), viewPoolInfo(), and withdraw().
getPoolRandom()
t_return MPools::getPoolRandom (t_storage s, const t_ipool ipool) inline
Get random number from source.
Definition at line 137 of file MPools.ligo.
References getPool(), MPool::getRandom(), MPool::mustManager(), and setPool().
Referenced by CPoolGames::main().
getUser()
t_user MPools::getUser (const t_storage s, const t_ipool ipool) inline
Get the current user parameters in the pool.
The user is identified by Tezos.sender
Definition at line 42 of file MPools.ligo.
References balance.
Referenced by deposit(), viewBalance(), and withdraw().
onBalance()
t_return MPools::onBalance (t_storage s, const MToken::t_amount currentBalance) inline
Processing a callback with a balance.
Definition at line 204 of file MPools.ligo.
References cNO_OPERATIONS, getPool(), MPool::onBalanceAfterHarvest(), MPool::onBalanceAfterTez2Burn(), MPool::onBalanceBeforeHarvest(), MPool::onBalanceBeforeTez2Burn(), and setPool().
Referenced by onBalanceFA1_2(), and onBalanceFA2().
onBalanceFA1_2()
t_return MPools::onBalanceFA1_2 (t_storage s, const MFA1_2::t_balance_callback_params currentBalance) inline
Callback with the FA1.2 token balance.
Definition at line 242 of file MPools.ligo.
References onBalance().
Referenced by CPoolGames::main().
onBalanceFA2()
t_return MPools::onBalanceFA2 (t_storage s, const MFA2::t_balance_callback_params params) inline
Callback with FA2 token balance.
Definition at line 247 of file MPools.ligo.
References cNO_OPERATIONS, and onBalance().
Referenced by CPoolGames::main().
onRandom()
t_return MPools::onRandom (t_storage s, const t_ipool ipool, const MRandom::t_random random) inline
Callback with random number for detect winner.
Definition at line 196 of file MPools.ligo.
References getPool(), MPool::onRandom(), and setPool().
Referenced by CPoolGames::main().
pausePool()
t_storage MPools::pausePool (const t_storage s, const t_ipool ipool) inline
Pause pool.
Definition at line 98 of file MPools.ligo.
References setPoolState().
Referenced by CPoolGames::main().
removePool()
t_storage MPools::removePool (t_storage s, const t_ipool ipool) inline
Remove pool (after game)
Definition at line 104 of file MPools.ligo.
References doRemovePool(), getPool(), MPool::mustManager(), and setPoolState().
Referenced by CPoolGames::main().
setPool()
t_storage MPools::setPool (t_storage s, const t_ipool ipool, const t_pool pool) inline
Update the pool by index.
Definition at line 32 of file MPools.ligo.
Referenced by afterReward2Tez(), changePoolManager(), deposit(), editPool(), getPoolRandom(), onBalance(), onRandom(), setPoolGameComplete(), setPoolState(), setPoolWinner(), and withdraw().
setPoolGameComplete()
t_return MPools::setPoolGameComplete (t_storage s, const t_ipool ipool) inline
Mark pool game complete by time.
Definition at line 129 of file MPools.ligo.
References getPool(), MPool::mustManager(), MPool::setGameComplete(), and setPool().
Referenced by CPoolGames::main().
setPoolState()
t_storage MPools::setPoolState (t_storage s, const t_ipool ipool, const t_pool_state state) inline
Set the pool state.
If you remove inline, the compiler crashes
Definition at line 71 of file MPools.ligo.
References getPool(), MPool::mustManager(), setPool(), and MPool::setState().
Referenced by pausePool(), removePool(), and startPool().
setPoolWinner()
t_return MPools::setPoolWinner (t_storage s, const t_ipool ipool, const address winner) inline
Set pool game winner.
Definition at line 145 of file MPools.ligo.
References getPool(), MPool::mustManager(), setPool(), and MPool::setPoolWinner().
Referenced by CPoolGames::main().
setUser()
t_storage MPools::setUser (t_storage s, const t_ipool ipool, const t_user user) inline
Update the current user parameters in the pool.
The user is identified by Tezos.sender. With zero saved balance, the user is deleted
Definition at line 59 of file MPools.ligo.
Referenced by deposit(), and withdraw().
startPool()
t_storage MPools::startPool (const t_storage s, const t_ipool ipool) inline
Play pool (after pause)
Definition at line 101 of file MPools.ligo.
References setPoolState().
Referenced by CPoolGames::main().
viewBalance()
nat MPools::viewBalance (const t_storage s, const t_ipool ipool) inline
Getting the user's balance in the pool.
Definition at line 288 of file MPools.ligo.
References getUser().
viewPoolInfo()
t_pool_info MPools::viewPoolInfo (const t_storage s, const t_ipool ipool) inline
Getting basic Pool information.
Definition at line 274 of file MPools.ligo.
References balance, and getPool().
withdraw()
t_return MPools::withdraw (t_storage s, const t_ipool ipool, const MToken::t_amount wamount) inline
Withdraw from pool.
Parameters
wamount Amount of tokens for withdraw from pool 0n == wamount - withdraw all deposit from pool
Definition at line 185 of file MPools.ligo.
References doRemovePool(), getPool(), getUser(), setPool(), setUser(), and MPool::withdraw().
Referenced by CPoolGames::main().
Member Data Documentation
balance
MPools::balance
Definition at line 290 of file MPools.ligo.
Referenced by getUser(), and viewPoolInfo().
cERR_FARM_USED
const string MPools::cERR_FARM_USED = "MPools/FarmUsed"
Error: You cannot use the same farms in pools.
Definition at line 16 of file MPools.ligo.
Referenced by createPool().
cERR_NOT_FOUND
const string MPools::cERR_NOT_FOUND = "MPools/NotFound"
Error: Pool not found.
Definition at line 12 of file MPools.ligo.
Referenced by getPool().
The documentation for this class was generated from the following file:
MPools.ligo