Pool Games: MRandom Class Reference
MRandom Class Reference
Module for interaction with a random number source.
Public Types
typedef address t_random_source
Address of the source of random numbers.
typedef t_i t_iobj
Object ID in the customer contract.
typedef timestamp t_ts
The time of the event for which a random number.
typedef pair< t_ts, t_iobj > t_ts_iobj
Event time and Object ID.
typedef nat t_random
Random number.
typedef pair< t_iobj, t_random > t_iobj_random
The type of callback for getting a random number.
typedef OnRandomCallback of t_iobj_random t_callback_params
typedef contract< t_callback_params > t_callback
typedef tuple< t_ts, t_iobj, t_callback > t_ts_iobj_callback
Event time, Object ID, and callback for a random number.
typedef RandomCreateFuture of t_ts_iobj t_create
Prototype of the createFuture method.
typedef contract< t_create > t_create_contract
Contract with createFuture entry point.
typedef RandomDeleteFuture of t_ts_iobj t_delete
Prototype of the deleteFuture method.
typedef contract< t_delete > t_delete_contract
Contract with the deleteFuture entry point.
typedef RandomGetFuture of t_ts_iobj_callback t_get
Prototype of the getFuture method.
typedef contract< t_get > t_get_contract
Contract with the getFuture entry point.
Public Member Functions
t_create_contract createFutureEntrypoint (const address addr)
Get the createFuture entry point.
t_create createParams (const t_ts ts, const t_iobj iobj)
Parameters for creating a random number request.
operation create (const address addr, const t_ts ts, const t_iobj iobj)
Operation of creating a random number request.
t_delete_contract deleteFutureEntrypoint (const address addr)
Get the deleteFuture entry point.
t_delete deleteParams (const t_ts ts, const t_iobj iobj)
Parameters for deleting a random number request.
operation delete (const address addr, const t_ts ts, const t_iobj iobj)
Operation of deleting a random number request.
t_get_contract getFutureEntrypoint (const address addr)
Get a getFuture entry point.
t_get getParams (const t_ts ts, const t_iobj iobj, const t_callback callback)
Parameters for getting a random number.
operation get (const address addr, const t_ts ts, const t_iobj iobj, const t_callback callback)
Operation of creating a random number request.
unit check (const t_random_source randomSource)
Checking the source of random numbers for validity.
Public Attributes
const string cERR_NOT_FOUND = "MRandom/NotFound"
Error: Source contract not found.
const string cERR_NOT_FOUND_CREATE = "MRandom/NotFoundCreateFuture"
Error: The createFuture token method was not found.
const string cERR_NOT_FOUND_DELETE = "MRandom/NotFoundDeleteFuture"
Error: Token deleteFuture method not found.
const string cERR_NOT_FOUND_GET = "MRandom/NotFoundGetFuture"
Error: Token getFuture method not found.
Detailed Description
Module for interaction with a random number source.
Definition at line 6 of file MRandom.ligo.
Member Typedef Documentation
t_callback
typedef contract<t_callback_params> MRandom::t_callback
Definition at line 44 of file MRandom.ligo.
t_callback_params
typedef OnRandomCallback of t_iobj_random MRandom::t_callback_params
Definition at line 43 of file MRandom.ligo.
t_create
typedef RandomCreateFuture of t_ts_iobj MRandom::t_create
Prototype of the createFuture method.
Definition at line 68 of file MRandom.ligo.
t_create_contract
typedef contract<t_create> MRandom::t_create_contract
Contract with createFuture entry point.
Definition at line 72 of file MRandom.ligo.
t_delete
typedef RandomDeleteFuture of t_ts_iobj MRandom::t_delete
Prototype of the deleteFuture method.
Definition at line 76 of file MRandom.ligo.
t_delete_contract
typedef contract<t_delete> MRandom::t_delete_contract
Contract with the deleteFuture entry point.
Definition at line 80 of file MRandom.ligo.
t_get
typedef RandomGetFuture of t_ts_iobj_callback MRandom::t_get
Prototype of the getFuture method.
Definition at line 84 of file MRandom.ligo.
t_get_contract
typedef contract<t_get> MRandom::t_get_contract
Contract with the getFuture entry point.
Definition at line 88 of file MRandom.ligo.
t_iobj
typedef t_i MRandom::t_iobj
Object ID in the customer contract.
Definition at line 14 of file MRandom.ligo.
t_iobj_random
typedef pair<t_iobj,t_random> MRandom::t_iobj_random
The type of callback for getting a random number.
Definition at line 42 of file MRandom.ligo.
t_random
typedef nat MRandom::t_random
Random number.
To create a random number, the hash of the nearest Tezos is taken, the time of which is greater than or equal to the time of the event, SHA-256 is removed from it, we get the levelHash value. Also, the SHA-256 hash is removed from the line "customer's address<space><object ID in the customer's contract in decimal notation>", we get the requestHash value. A random number is calculated as random = levelHash^ requestHash and converted to nat format. As a result, in general, we have a 256-bit random number
Definition at line 38 of file MRandom.ligo.
t_random_source
typedef address MRandom::t_random_source
Address of the source of random numbers.
Definition at line 10 of file MRandom.ligo.
t_ts
typedef timestamp MRandom::t_ts
The time of the event for which a random number.
Definition at line 18 of file MRandom.ligo.
t_ts_iobj
typedef pair<t_ts,t_iobj> MRandom::t_ts_iobj
Event time and Object ID.
Definition at line 22 of file MRandom.ligo.
t_ts_iobj_callback
typedef tuple<t_ts,t_iobj,t_callback> MRandom::t_ts_iobj_callback
Event time, Object ID, and callback for a random number.
Definition at line 48 of file MRandom.ligo.
Member Function Documentation
check()
unit MRandom::check (const t_random_source randomSource) inline
Checking the source of random numbers for validity.
Definition at line 159 of file MRandom.ligo.
References createFutureEntrypoint(), deleteFutureEntrypoint(), and getFutureEntrypoint().
Referenced by MPool::create(), and MPool::edit().
create()
operation MRandom::create (const address addr, const t_ts ts, const t_iobj iobj) inline
Operation of creating a random number request.
Definition at line 105 of file MRandom.ligo.
References createFutureEntrypoint(), and createParams().
Referenced by MPool::requestRandomIfNeed().
createFutureEntrypoint()
t_create_contract MRandom::createFutureEntrypoint (const address addr) inline
Get the createFuture entry point.
Definition at line 92 of file MRandom.ligo.
References cERR_NOT_FOUND_CREATE.
Referenced by check(), and create().
createParams()
t_create MRandom::createParams (const t_ts ts, const t_iobj iobj) inline
Parameters for creating a random number request.
Definition at line 100 of file MRandom.ligo.
Referenced by create().
delete()
operation MRandom::delete (const address addr, const t_ts ts, const t_iobj iobj) inline
Operation of deleting a random number request.
Definition at line 128 of file MRandom.ligo.
References deleteFutureEntrypoint(), and deleteParams().
deleteFutureEntrypoint()
t_delete_contract MRandom::deleteFutureEntrypoint (const address addr) inline
Get the deleteFuture entry point.
Definition at line 114 of file MRandom.ligo.
References cERR_NOT_FOUND_DELETE.
Referenced by check(), and delete().
deleteParams()
t_delete MRandom::deleteParams (const t_ts ts, const t_iobj iobj) inline
Parameters for deleting a random number request.
Definition at line 123 of file MRandom.ligo.
Referenced by delete().
get()
operation MRandom::get (const address addr, const t_ts ts, const t_iobj iobj, const t_callback callback) inline
Operation of creating a random number request.
Definition at line 150 of file MRandom.ligo.
References getFutureEntrypoint(), and getParams().
Referenced by MPool::getRandom().
getFutureEntrypoint()
t_get_contract MRandom::getFutureEntrypoint (const address addr) inline
Get a getFuture entry point.
Definition at line 137 of file MRandom.ligo.
References cERR_NOT_FOUND_GET.
Referenced by check(), and get().
getParams()
t_get MRandom::getParams (const t_ts ts, const t_iobj iobj, const t_callback callback) inline
Parameters for getting a random number.
Definition at line 145 of file MRandom.ligo.
Referenced by get().
Member Data Documentation
cERR_NOT_FOUND
const string MRandom::cERR_NOT_FOUND = "MRandom/NotFound"
Error: Source contract not found.
Definition at line 52 of file MRandom.ligo.
cERR_NOT_FOUND_CREATE
const string MRandom::cERR_NOT_FOUND_CREATE = "MRandom/NotFoundCreateFuture"
Error: The createFuture token method was not found.
Definition at line 56 of file MRandom.ligo.
Referenced by createFutureEntrypoint().
cERR_NOT_FOUND_DELETE
const string MRandom::cERR_NOT_FOUND_DELETE = "MRandom/NotFoundDeleteFuture"
Error: Token deleteFuture method not found.
Definition at line 60 of file MRandom.ligo.
Referenced by deleteFutureEntrypoint().
cERR_NOT_FOUND_GET
const string MRandom::cERR_NOT_FOUND_GET = "MRandom/NotFoundGetFuture"
Error: Token getFuture method not found.
Definition at line 64 of file MRandom.ligo.
Referenced by getFutureEntrypoint().
The documentation for this class was generated from the following file:
MRandom.ligo