Pool Games: MAdmin Class Reference
MAdmin Class Reference
Contract admin management module.
Public Types
typedef address t_admin
Contract admin.
Public Member Functions
bool isAdmin (const t_admin admin)
Is the current user an admin.
unit mustAdmin (const t_admin admin)
The current user must have admin rights.
t_admin accessChange (const t_admin newadmin, t_admin admin)
Admin change with admin rights check.
Public Attributes
const string cERR_DENIED = "MAdmin/Denied"
Error: Access denied.
Detailed Description
Contract admin management module.
The admin or the owner can replace the admin with another one Example using a module without other access modules
#Include "module/MAdmin.ligo"
type t_storage record [
    admin: MAdmin.t_admin;
    ...
];
type t_entrypoint is
| ChangeAdmin of MAdmin.t_admin
...
function main(const entrypoint: t_entrypoint; var s: t_storage): t_return is
case entrypoint of
| ChangeAdmin(params) -> (cNO_OPERATIONS, { s.admin:= MAdmin.accessChange(params, s.admin); } with s)
...
Definition at line 28 of file MAdmin.ligo.
Member Typedef Documentation
t_admin
typedef address MAdmin::t_admin
Contract admin.
Definition at line 30 of file MAdmin.ligo.
Member Function Documentation
accessChange()
t_admin MAdmin::accessChange (const t_admin newadmin, t_admin admin) inline
Admin change with admin rights check.
Definition at line 52 of file MAdmin.ligo.
References mustAdmin().
isAdmin()
bool MAdmin::isAdmin (const t_admin admin) inline
Is the current user an admin.
Definition at line 36 of file MAdmin.ligo.
Referenced by CPoolGames::isAdmin(), and mustAdmin().
mustAdmin()
unit MAdmin::mustAdmin (const t_admin admin) inline
The current user must have admin rights.
If the user is not an admin, the error cERR_DENIED will be returned
Definition at line 44 of file MAdmin.ligo.
References cERR_DENIED, and isAdmin().
Referenced by accessChange(), and CPoolGames::mustAdmin().
Member Data Documentation
cERR_DENIED
const string MAdmin::cERR_DENIED = "MAdmin/Denied"
Error: Access denied.
Definition at line 32 of file MAdmin.ligo.
Referenced by mustAdmin().
The documentation for this class was generated from the following file:
MAdmin.ligo