Pool Games: MPoolOpts Class Reference
MPoolOpts Class Reference
Pool options.
Public Member Functions
unit check (const t_opts opts)
Checking the pool parameters for validity.
bool maybeNoBurn (const t_opts opts)
Can a pool not have a token to burn.
bool maybeNoFeeAddr (const t_opts opts)
Can a pool not have an address for a commission.
Public Attributes
const string cERR_INVALID_SECONDS = "MPoolOpts/InvalidSeconds"
Error: Invalid number of seconds.
const string cERR_INVALID_MIN_SECONDS = "MPoolOpts/InvalidMinSeconds"
Error: Invalid minimum number of seconds.
const string cERR_INVALID_MAX_DEPOSIT = "MPoolOpts/InvalidMaxDeposit"
Error: The maximum deposit is less than the minimum.
const string cERR_INVALID_PERCENT = "MPoolOpts/InvalidPercent"
Error: The sum of the winner's percentage+burning+commission is not equal to 100.
Detailed Description
Pool options.
Definition at line 6 of file MPoolOpts.ligo.
Member Function Documentation
check()
unit MPoolOpts::check (const t_opts opts) inline
Checking the pool parameters for validity.
Definition at line 26 of file MPoolOpts.ligo.
References cERR_INVALID_MAX_DEPOSIT, cERR_INVALID_MIN_SECONDS, cERR_INVALID_PERCENT, and cERR_INVALID_SECONDS.
Referenced by MPool::create(), and MPool::edit().
maybeNoBurn()
bool MPoolOpts::maybeNoBurn (const t_opts opts) inline
Can a pool not have a token to burn.
If the percentage of burning is 0, then the token is not needed for burning
Definition at line 46 of file MPoolOpts.ligo.
Referenced by MPool::create(), and MPool::edit().
maybeNoFeeAddr()
bool MPoolOpts::maybeNoFeeAddr (const t_opts opts) inline
Can a pool not have an address for a commission.
If the percentage of remuneration is 0, then the address for the commission is not needed
Definition at line 54 of file MPoolOpts.ligo.
Referenced by MPool::create().
Member Data Documentation
cERR_INVALID_MAX_DEPOSIT
const string MPoolOpts::cERR_INVALID_MAX_DEPOSIT = "MPoolOpts/InvalidMaxDeposit"
Error: The maximum deposit is less than the minimum.
Definition at line 18 of file MPoolOpts.ligo.
Referenced by check().
cERR_INVALID_MIN_SECONDS
const string MPoolOpts::cERR_INVALID_MIN_SECONDS = "MPoolOpts/InvalidMinSeconds"
Error: Invalid minimum number of seconds.
Definition at line 14 of file MPoolOpts.ligo.
Referenced by check().
cERR_INVALID_PERCENT
const string MPoolOpts::cERR_INVALID_PERCENT = "MPoolOpts/InvalidPercent"
Error: The sum of the winner's percentage+burning+commission is not equal to 100.
Definition at line 22 of file MPoolOpts.ligo.
Referenced by check().
cERR_INVALID_SECONDS
const string MPoolOpts::cERR_INVALID_SECONDS = "MPoolOpts/InvalidSeconds"
Error: Invalid number of seconds.
Definition at line 10 of file MPoolOpts.ligo.
Referenced by check().
The documentation for this class was generated from the following file:
MPoolOpts.ligo