Pool Games: MFA1_2 Class Reference
MFA1_2 Class Reference
Types and methods for FA1.2.
Classes
struct t_approve_params
Input parameters for the approve method.
struct t_balance_params
Input parameters for the balance method.
struct t_transfer_params
Input parameters for the transfer method.
Public Types
typedef FA12Transfer of t_transfer_params t_transfer_method
Prototype of the transfer method.
typedef contract< t_transfer_method > t_transfer_contract
Contract with the transfer entry point.
typedef nat t_balance_callback_params
Balance Callback Parameters.
typedef contract< t_balance_callback_params > t_balance_callback
The type of callback to get the balance.
typedef FA12Balance of t_balance_params t_balance_method
Prototype of the balance method.
typedef contract< t_balance_method > t_balance_contract
Contract with the balance entry point.
typedef FA12Approve of t_approve_params t_approve_method
Prototype of the approve method.
typedef contract< t_approve_method > t_approve_contract
Contract with the approve entry point.
Public Member Functions
t_transfer_contract transferEntrypoint (const address addr)
Get the transfer token entry point.
t_transfer_method transferParams (const address src, const address dst, const nat tamount)
Parameters for transferring tokens.
operation transfer (const address token, const address src, const address dst, const nat tamount)
Token Transfer Operation.
t_balance_contract balanceEntrypoint (const address addr)
Get the balance token entry point.
t_balance_method balanceParams (const address owner, const t_balance_callback callback)
Parameters for balance request.
operation balanceOf (const address token, const address owner, const t_balance_callback callback)
Token Transfer Operation.
t_approve_contract approveEntrypoint (const address addr)
Get the approve token entry point.
t_approve_method approveParams (const address operator,const nat tamount)
Parameters for approving the disposal of tokens.
operation approve (const address token, const address operator,const nat tamount)
The operation of approving the disposal of tokens.
operation decline (const address token, const address operator)
The operation of prohibiting the disposal of tokens.
unit check (const address token)
Checking for compliance with the FA1.2 standard.
Public Attributes
const string cERR_NOT_FOUND_TRANSFER = "MFA1_2/NotFoundTransfer"
Error: The token transfer method was not found.
const string cERR_NOT_FOUND_BALANCE = "MFA1_2/NotFoundBalance"
Error: The balance token method was not found.
const string cERR_NOT_FOUND_APPROVE = "MFA1_2/NotFoundApprove"
Error: The approve token method was not found.
Detailed Description
Types and methods for FA1.2.
Definition at line 6 of file MFA1_2.ligo.
Member Typedef Documentation
t_approve_contract
typedef contract<t_approve_method> MFA1_2::t_approve_contract
Contract with the approve entry point.
Definition at line 70 of file MFA1_2.ligo.
t_approve_method
typedef FA12Approve of t_approve_params MFA1_2::t_approve_method
Prototype of the approve method.
Definition at line 66 of file MFA1_2.ligo.
t_balance_callback
typedef contract<t_balance_callback_params> MFA1_2::t_balance_callback
The type of callback to get the balance.
Definition at line 36 of file MFA1_2.ligo.
t_balance_callback_params
typedef nat MFA1_2::t_balance_callback_params
Balance Callback Parameters.
Definition at line 32 of file MFA1_2.ligo.
t_balance_contract
typedef contract<t_balance_method> MFA1_2::t_balance_contract
Contract with the balance entry point.
Definition at line 55 of file MFA1_2.ligo.
t_balance_method
typedef FA12Balance of t_balance_params MFA1_2::t_balance_method
Prototype of the balance method.
Definition at line 51 of file MFA1_2.ligo.
t_transfer_contract
typedef contract<t_transfer_method> MFA1_2::t_transfer_contract
Contract with the transfer entry point.
Definition at line 28 of file MFA1_2.ligo.
t_transfer_method
typedef FA12Transfer of t_transfer_params MFA1_2::t_transfer_method
Prototype of the transfer method.
Definition at line 24 of file MFA1_2.ligo.
Member Function Documentation
approve()
operation MFA1_2::approve (const address token, const address operator, const nat tamount) inline
The operation of approving the disposal of tokens.
Definition at line 145 of file MFA1_2.ligo.
References approveEntrypoint(), and approveParams().
Referenced by MToken::approve().
approveEntrypoint()
t_approve_contract MFA1_2::approveEntrypoint (const address addr) inline
Get the approve token entry point.
Definition at line 129 of file MFA1_2.ligo.
References cERR_NOT_FOUND_APPROVE.
Referenced by approve(), check(), and decline().
approveParams()
t_approve_method MFA1_2::approveParams (const address operator, const nat tamount) inline
Parameters for approving the disposal of tokens.
Definition at line 137 of file MFA1_2.ligo.
Referenced by approve(), and decline().
balanceEntrypoint()
t_balance_contract MFA1_2::balanceEntrypoint (const address addr) inline
Get the balance token entry point.
Definition at line 104 of file MFA1_2.ligo.
References cERR_NOT_FOUND_BALANCE.
Referenced by balanceOf(), and check().
balanceOf()
operation MFA1_2::balanceOf (const address token, const address owner, const t_balance_callback callback) inline
Token Transfer Operation.
Definition at line 120 of file MFA1_2.ligo.
References balanceEntrypoint(), and balanceParams().
Referenced by MToken::balanceOf().
balanceParams()
t_balance_method MFA1_2::balanceParams (const address owner, const t_balance_callback callback) inline
Parameters for balance request.
Definition at line 112 of file MFA1_2.ligo.
Referenced by balanceOf().
check()
unit MFA1_2::check (const address token) inline
Checking for compliance with the FA1.2 standard.
Definition at line 163 of file MFA1_2.ligo.
References approveEntrypoint(), balanceEntrypoint(), and transferEntrypoint().
Referenced by MToken::check().
decline()
operation MFA1_2::decline (const address token, const address operator) inline
The operation of prohibiting the disposal of tokens.
Definition at line 154 of file MFA1_2.ligo.
References approveEntrypoint(), and approveParams().
Referenced by MToken::decline().
transfer()
operation MFA1_2::transfer (const address token, const address src, const address dst, const nat tamount) inline
Token Transfer Operation.
Definition at line 95 of file MFA1_2.ligo.
References transferEntrypoint(), and transferParams().
Referenced by MToken::burn(), and MToken::transfer().
transferEntrypoint()
t_transfer_contract MFA1_2::transferEntrypoint (const address addr) inline
Get the transfer token entry point.
Definition at line 78 of file MFA1_2.ligo.
References cERR_NOT_FOUND_TRANSFER.
Referenced by check(), and transfer().
transferParams()
t_transfer_method MFA1_2::transferParams (const address src, const address dst, const nat tamount) inline
Parameters for transferring tokens.
Definition at line 86 of file MFA1_2.ligo.
Referenced by transfer().
Member Data Documentation
cERR_NOT_FOUND_APPROVE
const string MFA1_2::cERR_NOT_FOUND_APPROVE = "MFA1_2/NotFoundApprove"
Error: The approve token method was not found.
Definition at line 74 of file MFA1_2.ligo.
Referenced by approveEntrypoint().
cERR_NOT_FOUND_BALANCE
const string MFA1_2::cERR_NOT_FOUND_BALANCE = "MFA1_2/NotFoundBalance"
Error: The balance token method was not found.
Definition at line 73 of file MFA1_2.ligo.
Referenced by balanceEntrypoint().
cERR_NOT_FOUND_TRANSFER
const string MFA1_2::cERR_NOT_FOUND_TRANSFER = "MFA1_2/NotFoundTransfer"
Error: The token transfer method was not found.
Definition at line 72 of file MFA1_2.ligo.
Referenced by transferEntrypoint().
The documentation for this class was generated from the following file:
MFA1_2.ligo